# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        main-config:
            toolbar:
                - {name: "styles", items: ['Styles',
                'Format', 'Font', 'FontSize', '-','Bold', 'Italic', 'Underline', 'Strike',
                'Blockquote', '-', 'Link', '-', 'JustifyLeft', 'JustifyCenter',
                'JustifyRight', 'JustifyBlock', '-', 'NumberedList', 'BulletedList',
                '-', 'Outdent', 'Indent', '-', 'Image', 'Table', '-', 'TextColor', 'BGColor']}
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
